name: wine-macports

on:
  workflow_dispatch:

env:
  CC: clang
  CXX: false  # no c++ code

jobs:
  macos:
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: macos-11
          - os: macos-12
          - os: macos-13
    runs-on: ${{ matrix.config.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install MacPorts
        run: |
          curl -LO https://raw.githubusercontent.com/GiovanniBussi/macports-ci/master/macports-ci
          source ./macports-ci install

      - name: Adding MacPorts into $PATH
        run: |
          set -x
          echo "/opt/local/bin" >> $GITHUB_PATH
          echo "/opt/local/sbin" >> $GITHUB_PATH

      - name: Install MacPorts-Wine overlay
        run: bash -ex install_overlay.sh

      - name: Build Wine
        run: sudo port -v install wine-devel
        
      - name: Get Wine package path
        run: |
          set -x
          echo "WINEPATH=$(port -q location wine-devel)" >> $GITHUB_ENV
          echo "WINEPKG=$(basename $(port -q location wine-devel) .tbz2)" >> $GITHUB_ENV

      - name: Upload Wine
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.WINEPKG }}.${{ matrix.config.os }}.tar.bz2
          path: ${{ env.WINEPATH }}
